### PR TITLE
fix(backend): quadlet parsing logic

### LINKED ISSUE #1425: Quadlet Extension: Quadlet entries become invisible when using many Environment keys
EDIT: I found the exact problem: Even this single line causes to disappear all items in the list:

`# --- Primary Properties ---`

But this one fixes it:

`# --- Primary Properties --`

I think 3 dashes at the end of a line somehow breaks the parser?

### Bug description

When a .container file contains many Environment= entries (e.g., 30+ for a socket-proxy), the Quadlet disappears from the "Quadlets" list in Podman Desktop. (No Quadlets found on your system)

It also causes to disappear all other quadlets which are not triggering the bug. 

Steps to reproduce:

    Create a Quadlet with 30+ Environment=KEY=VALUE lines.

    Run systemctl --user daemon-reload.

    Check Podman Desktop Quadlet list.

Actual behavior: The Quadlet is invisible in the UI, even though systemctl --user start works perfectly via CLI. The generated running container also appears unter "Containers" in the app. 

Expected behavior:  The UI should parse and display the Quadlet regardless of the number of environment variables, matching systemd's behavior.

Environment:
    Podman version: 5.8.2
    Podman Desktop version: 1.26.2

### Operating system

Fedora 43

### Installation Method

Flathub (Linux)

### Version

1.26.0

### Steps to reproduce

This one causes the quadlet to disappear in the ui:

```
[Unit]
Description=Socket Proxy for Authentik (Rootless)

[Container]
# --- Primary Properties ---
Image=lscr.io/linuxserver/socket-proxy:latest
ContainerName=socket-proxy_authentik
ReadOnly=true

# --- Storage & Mounts ---
Tmpfs=/run
Volume=/run/user/1000/podman/podman.sock:/var/run/docker.sock:ro,z

# --- Environment Variables (Repeating Keys) ---
Environment=TZ=Etc/UTC
Environment=ALLOW_START=1
Environment=ALLOW_STOP=1
Environment=ALLOW_RESTARTS=1
Environment=ALLOW_PAUSE=0
Environment=ALLOW_UNPAUSE=0
Environment=AUTH=0
Environment=BUILD=0
Environment=COMMIT=0
Environment=CONFIGS=0
Environment=CONTAINERS=1
Environment=DISABLE_IPV6=0
Environment=DISTRIBUTION=0
Environment=EVENTS=1
Environment=EXEC=0
Environment=IMAGES=1
Environment=INFO=1
Environment=LOG_LEVEL=info
Environment=NETWORKS=0
Environment=NODES=0
Environment=PING=1
Environment=PLUGINS=0
Environment=POST=1
Environment=SECRETS=0
Environment=SERVICES=0
Environment=SESSION=0
Environment=SWARM=0
Environment=SYSTEM=0
Environment=TASKS=0
Environment=VERSION=1
Environment=VOLUMES=0

[Service]
Restart=always

[Install]
WantedBy=default.target
```

Then tried to fix it by shortening the lines:
```
[Unit]
Description=Socket Proxy for Authentik (Rootless)

[Container]
# --- Primary Properties ---
Image=lscr.io/linuxserver/socket-proxy:latest
ContainerName=socket-proxy_authentik
ReadOnly=true

# --- Storage & Mounts ---
# Dedicated Quadlet key for tmpfs
Tmpfs=/run
# Socket mount with read-only and SELinux labeling
Volume=/run/user/1000/podman/podman.sock:/var/run/docker.sock:ro,z

# --- Environment Variables ---
EnvironmentFile=socket-proxy_authentik.env

[Service]
# Ensures the service is always resurrected regardless of exit code
Restart=always

[Install]
# Links service to the user's session/boot
WantedBy=default.target
```

Still causing the same problem, finally this one causes to it to appear finally:

```
[Unit]
Description=Socket Proxy for Authentik

[Container]
Image=lscr.io/linuxserver/socket-proxy:latest
ContainerName=socket-proxy_authentik
ReadOnly=true
Tmpfs=/run
Volume=/run/user/1000/podman/podman.sock:/var/run/docker.sock:ro,z
EnvironmentFile=./socket-proxy_authentik.env

[Service]
Restart=always

[Install]
WantedBy=default.target
```

### Relevant log output

```shell

```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by axel7083**
## Description

Update the way we parse quadlets dryrun output to be more robust.

## Related issues

Fixes https://github.com/podman-desktop/extension-podman-quadlet/issues/1425

## Testing

- [x] unit tests ensure no regression

> Regression test has been added

### CODE REVIEW

File: packages/backend/src/utils/parsers/quadlet-dryrun-parser.ts [hunk 1]
```diff
@@ -28,18 +28,34 @@ export class QuadletDryRunParser extends Parser<RunResult & { exitCode?: number
...
+
+    for (const line of lines) {
+      const match = regex.exec(line);
+      if (match) {
+        flush();
+
+        serviceName = match[1].trim();
+        buffer = undefined;
+      } else {
+        buffer = buffer ? buffer + '\n' + line : line;
```
Comment (benoitf) [inline packages/backend/src/utils/parsers/quadlet-dryrun-parser.ts]: question: should it use `${buffer}\n${line}`

**Review by benoitf — APPROVED** [review]

File: packages/backend/src/utils/parsers/quadlet-dryrun-parser.ts (hunk 1 above)
Comment (axel7083) [reply packages/backend/src/utils/parsers/quadlet-dryrun-parser.ts]: Not really because buffer can be undefined on the first pass (if the suggestion was to replace the all line) but we could have

```suggestion
        buffer = buffer ? `${buffer}\n${line}` : line;
```
